apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::$AWS_ACCOUNT_ID:role/document-api-eks-node-group-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::$AWS_ACCOUNT_ID:role/OIDC
      username: github-actions
      groups:
      - system:masters
