apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::771826808000:role/document-api-eks-node-group-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::771826808000:role/OIDC
      username: github-actions
      groups:
      - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::771826808000:user/july2025
      username: july2025
      groups:
      - system:masters
